# -*- coding: utf-8 -*-
"""Traning_data_validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kjdw4ayfeRIFIAxcrwA7gZRlDS9E1L9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 设置地区对应的 UTC 偏移量（小时）
region_offset = {
    "Africa and Middle East": 2,       # UTC+2
    "Asia and Pacific": 8,             # UTC+8
    "Europe": 2,                       # UTC+2 (Central European Summer Time)
    "Latin America and Caribbean": -4,  # UTC-4
    "North America": -6                # UTC-6
}

# 读取数据
df = pd.read_csv("final_training_data.csv")

# 将 pct_hour_0 到 pct_hour_23 中的 NaN 填充为 0
hour_cols = [f"pct_hour_{h}" for h in range(24)]
df[hour_cols] = df[hour_cols].fillna(0)

# 为每个地区计算加权平均的活动曲线
# 结果存储在一个字典中：region -> 长度为24的数组，表示本地时间每个小时的平均交易比例
activity_profiles = {}

for region in region_offset.keys():
    # 筛选该地区的钱包
    region_df = df[df["final_label"] == region]

    if len(region_df) == 0:
        print(f"警告: 地区 {region} 没有数据")
        activity_profiles[region] = np.zeros(24)
        continue

    # 获取偏移量
    offset = region_offset[region]

    # 将 UTC 小时转换为本地时间小时
    # 原始列: pct_hour_0 (UTC 0点) 对应本地时间 (0+offset) mod 24
    # 对于每个本地时间小时 local_h，它对应 UTC 小时 (local_h - offset) mod 24
    local_profile = np.zeros(24)

    for local_h in range(24):
        # 计算对应的 UTC 小时
        utc_h = (local_h - offset) % 24
        # 该本地小时的交易比例 = 对应 UTC 小时的比例
        # 需要按交易笔数加权，所以先取得每个钱包在该 UTC 小时的比例
        proportions = region_df[f"pct_hour_{utc_h}"].values
        weights = region_df["total_transactions"].values
        # 计算加权平均 (处理全零权重的情况)
        if weights.sum() > 0:
            weighted_avg = np.average(proportions, weights=weights)
        else:
            weighted_avg = 0
        local_profile[local_h] = weighted_avg

    activity_profiles[region] = local_profile

# 绘图
plt.figure(figsize=(14, 8))
colors = {
    "Africa and Middle East": "orange",
    "Asia and Pacific": "red",
    "Europe": "blue",
    "Latin America and Caribbean": "green",
    "North America": "purple"
}

for region, profile in activity_profiles.items():
    plt.plot(range(24), profile * 100, label=region, color=colors.get(region, "gray"), linewidth=2)

plt.xlabel("Local Time (Hour of Day)", fontsize=12)
plt.ylabel("% of Transactions (Weighted by Wallet Transaction Count)", fontsize=12)
plt.title("Activity Profile for Wallets Identified through Regional Exchanges", fontsize=14)
plt.xticks(range(0, 24, 2))
plt.grid(True, alpha=0.3)
plt.legend(loc="upper right")
plt.tight_layout()
plt.show()

# 可选：打印每个地区活跃峰值时间
print("\n各地区活动峰值本地时间（交易加权）:")
for region, profile in activity_profiles.items():
    peak_hour = np.argmax(profile)
    peak_value = profile[peak_hour] * 100
    print(f"{region}: 本地时间 {peak_hour}:00, 占比 {peak_value:.2f}%")